[package]
name = "rust-kata-004"
version = "0.1.0"
authors = ["agabani <agabani@users.noreply.github.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
name = "rust-kata-004"
path = "src/main.rs"

[[bin]]
name = "tor-stub"
path = "src/tor_stub.rs"

[dependencies]
libc = { version = "0.2.86", features = [] }
signal-hook = { version = "0.3.6", features = ["channel"] }
tokio = { version = "1.2.0", features = ["macros", "process", "rt-multi-thread", "time"] }

[dev-dependencies]
fake = "2.4.0"
